name: freelance
description: Plugin Flutter qui contient l'ensemble de mes outils de réalisation d'application web et mobile.
version: 1.0.0+6
homepage: https://freelance.benoitfontaine.fr/
repository: https://github.com/benoit-fontaine/freelance

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  animations: ^2.0.11
  animator: ^3.3.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.18+3
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.2.3
  go_router: ^13.0.1
  nil: ^1.1.1 
  intl: ^0.18.1 
  get_it: ^7.6.6
  widgetbook: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  bdd_widget_test: ^1.6.3

flutter:
  plugin:
    platforms:
      android:
        package: fr.benoitfontaine.freelance
        pluginClass: FreelancePlugin
      ios:
        pluginClass: FreelancePlugin
      linux:
        pluginClass: FreelancePlugin
      macos:
        pluginClass: FreelancePlugin
      windows:
        pluginClass: FreelancePluginCApi
      web:
        pluginClass: FreelanceWeb
        fileName: method_channels/freelance_web.dart
        