name: freelance
description: Plugin Flutter qui contient l'ensemble de mes outils de réalisation
  d'application web et mobile.
version: 1.0.0+7
homepage: https://freelance.benoitfontaine.fr/
repository: https://github.com/benoit-fontaine/freelance

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  animations: ^2.0.11
  animator: ^3.3.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  firebase_storage: ^12.4.3
  flutter_bloc: ^9.0.0
  flutter_markdown: ^0.7.6+2
  get_it: ^8.0.3
  go_router: ^14.8.0
  intl: 
  nil: ^1.1.1
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.1
  widgetbook: ^3.11.0

dev_dependencies:
  bdd_widget_test: ^1.8.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.benoitfontaine.freelance
        pluginClass: FreelancePlugin
      ios:
        pluginClass: FreelancePlugin
      linux:
        pluginClass: FreelancePlugin
      macos:
        pluginClass: FreelancePlugin
      windows:
        pluginClass: FreelancePluginCApi
      web:
        pluginClass: FreelanceWeb
        fileName: method_channels/freelance_web.dart