name: freelance
description: Plugin Flutter qui contient l'ensemble de mes outils de réalisation d'application web et mobile.
version: 1.0.0
homepage: https://freelance.benoitfontaine.fr/

environment:
  sdk: '>=3.0.5'
  flutter: ">=3.10.5"

dependencies:
  animations: ^2.0.7
  animator: ^3.3.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.17
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
  url_launcher: ^6.1.12
  go_router: ^10.0.0 
  nil: ^1.1.1 
  intl: ^0.18.0 # ne pas mettre à jour pour le moment
  get_it: ^7.6.0
  widgetbook: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  bdd_widget_test: ^1.6.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.benoitfontaine.freelance
        pluginClass: FreelancePlugin
      ios:
        pluginClass: FreelancePlugin
      linux:
        pluginClass: FreelancePlugin
      macos:
        pluginClass: FreelancePlugin
      windows:
        pluginClass: FreelancePluginCApi
      web:
        pluginClass: FreelanceWeb
        fileName: method_channels/freelance_web.dart
        